name: Release Windows

on:
  push:
    tags:
      - 'windows-v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Archive Windows build
        run: Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath themisto-windows.zip
        shell: pwsh

      - uses: softprops/action-gh-release@v2
        with:
          files: themisto-windows.zip
          generate_release_notes: true
